### ISSUE TITLE
Missing OrCAD requirements?

### ISSUE THREAD

**Issue by topherbuckley** [fjullien/orlib2ki#1]
With the recent removal of [OrCAD lite](https://www.orcad.com/resources/download-orcad-lite), we are left with the options for OrCAD Viewer, and a free trial. Will your tool work with the OrCAD Viewer or does this require a full OrCAD license to work? 

Looks like the OrCAD Viewer is only available in .exe (windows) as well. Not sure how to use your tool on Linux as it stands. Any suggestions?

**Comment by fjullien** [comment]
First you need to know if OrCAD Viewer can export libraries as XML.
Then, if you want to use orlib2ki on Linux you just have to clone this repository and build the tool as decribed in the README file.

**Comment by fjullien** [comment]
If you don't have a lot do, I can convert the file for you.

**Comment by topherbuckley** [comment]
Yes yes, but as the OrCAD Viewer only seems to come in an .exe variety, I cannot open it to test if it can export or not. Just curious as you have build instructions for Linux, if you have a Linux based OrCAD option that works? Or is it required to boot a Windows machine to do the XML conversion and boot back into a Linux machine to do the XML-> KiCAD conversion?

**Comment by fjullien** [comment]
Sorry, I now see what you meant.
No, I dont' have any OrCAD running on Linux. I used Linux to develop this tool but I'm using it exclusively under Windows.

**Comment by topherbuckley** [comment]
I see. Thanks for the clarification. I'll have to develop a cross platform workflow then. Thanks for the tool though. I hope to make good use of it!
